spring:
  output.ansi.enabled: always
  profiles:
    active: local # 기본 환경 선택
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:file:.\build\database\moviedb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
    max-size: 10MB
    max-history: 30
---
spring:
  profiles: local
logging:
  root: debug
  file: ./log/local
---
spring:
  profiles: development
logging:
  root: debug
  file: ./log/development
---
spring:
  profiles: production
logging:
  root: info
  file: ./log/production