spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:file:C:\web\movie\build\moviedb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect